version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PORT: 3310
      WORDPRESS_DB_NAME: dbalcar
      WORDPRESS_DB_USER: usralcar
      WORDPRESS_DB_PASSWORD: 123456789
      file_uploads: On
      memory_limit: 64M
      upload_max_filesize: 64M
      post_max_size: 64M
      max_execution_time: 600
    volumes:
      - ./alcar:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
  mysql:
    image: mysql:latest
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: dbalcar
      MYSQL_USER: usralcar
      MYSQL_PASSWORD: 123456789
    volumes:
      - ./mysql:/var/lib/mysql