version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_PORT: 3310
      WORDPRESS_DB_NAME: dbalcar
      WORDPRESS_DB_USER: usralcar
      WORDPRESS_DB_PASSWORD: 123456789
    volumes:
      - ./alcar:/var/www/html
  mysql:
    image: mysql:latest
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: dbalcar
      MYSQL_USER: usralcar
      MYSQL_PASSWORD: 123456789
    volumes:
      - ./mysql:/var/lib/mysql